{{foreach from=$res item=e}}
    <tr>
        <td>{{$e.date}}</td>
        <td>{{$e.responseTime}}</td>
        <td>{{$e.usedCpuSys}}</td>
        <td>{{$e.connectedClients}}</td>
        <td>{{$e.blockedClients}}</td>
        <td>{{$e.usedMemory}}</td>
        <td>{{$e.usedMemoryRss}}</td>
        <td>{{$e.usedMemoryPeak}}</td>
        <td>{{$e.memFragmentationRatio}}</td>
        <td>{{$e.aofEnabled}}</td>
        <td>{{$e.totalConnectionsReceived}}</td>
        <td>{{$e.totalCommandsProcessed}}</td>
        <td>{{$e.instantaneousOpsPerSec}}</td>
        <td>{{$e.totalNetInputBytes}}</td>
        <td>{{$e.totalNetOutputBytes}}</td>
        <td>{{$e.instantaneousInputKbps}}</td>
        <td>{{$e.instantaneousOutputKbps}}</td>
        <td>{{$e.rejectedConnections}}</td>
        <td>{{$e.syncFull}}</td>
        <td>{{$e.syncPartialOk}}</td>
        <td>{{$e.syncPartialErr}}</td>
        <td>{{$e.expiredKeys}}</td>
        <td>{{$e.evictedKeys}}</td>
        <td>{{$e.keyspaceHits}}</td>
        <td>{{$e.keyspaceMisses}}</td>
        <td>{{$e.pubsubChannels}}</td>
        <td>{{$e.pubsubPatterns}}</td>
        <td>{{$e.latestForkUsec}}</td>
        <td>{{$e.migrateCachedSockets}}</td>
        <td>{{$e.usedCpuUser}}</td>
        <td>{{$e.usedCpuSysChildren}}</td>
        <td>{{$e.usedCpuUserChildren}}</td>
        <td>{{$e.totalKeys}}</td>
    </tr>
{{/foreach}}